require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TagsController do

  def mock_tagz(stubs={})
    @mock_tagz ||= mock_model(Tag, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tagzs as @tagzs" do
      Tag.stub(:all) { [mock_tagz] }
      get :index
      assigns(:tagzs).should eq([mock_tagz])
    end
  end

  describe "GET show" do
    it "assigns the requested tagz as @tagz" do
      Tag.stub(:find).with("37") { mock_tagz }
      get :show, :id => "37"
      assigns(:tagz).should be(mock_tagz)
    end
  end

  describe "GET new" do
    it "assigns a new tagz as @tagz" do
      Tag.stub(:new) { mock_tagz }
      get :new
      assigns(:tagz).should be(mock_tagz)
    end
  end

  describe "GET edit" do
    it "assigns the requested tagz as @tagz" do
      Tag.stub(:find).with("37") { mock_tagz }
      get :edit, :id => "37"
      assigns(:tagz).should be(mock_tagz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tagz as @tagz" do
        Tag.stub(:new).with({'these' => 'params'}) { mock_tagz(:save => true) }
        post :create, :tagz => {'these' => 'params'}
        assigns(:tagz).should be(mock_tagz)
      end

      it "redirects to the created tagz" do
        Tag.stub(:new) { mock_tagz(:save => true) }
        post :create, :tagz => {}
        response.should redirect_to(tagz_url(mock_tagz))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tagz as @tagz" do
        Tag.stub(:new).with({'these' => 'params'}) { mock_tagz(:save => false) }
        post :create, :tagz => {'these' => 'params'}
        assigns(:tagz).should be(mock_tagz)
      end

      it "re-renders the 'new' template" do
        Tag.stub(:new) { mock_tagz(:save => false) }
        post :create, :tagz => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tagz" do
        Tag.stub(:find).with("37") { mock_tagz }
        mock_tagz.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tagz => {'these' => 'params'}
      end

      it "assigns the requested tagz as @tagz" do
        Tag.stub(:find) { mock_tagz(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tagz).should be(mock_tagz)
      end

      it "redirects to the tagz" do
        Tag.stub(:find) { mock_tagz(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tagz_url(mock_tagz))
      end
    end

    describe "with invalid params" do
      it "assigns the tagz as @tagz" do
        Tag.stub(:find) { mock_tagz(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tagz).should be(mock_tagz)
      end

      it "re-renders the 'edit' template" do
        Tag.stub(:find) { mock_tagz(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tagz" do
      Tag.stub(:find).with("37") { mock_tagz }
      mock_tagz.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tagzs list" do
      Tag.stub(:find) { mock_tagz }
      delete :destroy, :id => "1"
      response.should redirect_to(tagzs_url)
    end
  end

end
